{
    "name": "OdooCC 网站中国生态增强验收",
    "version": "19.0.1.0.1",
    "category": "Tools",
    "summary": "验收 OdooCC 网站中国生态增强的公开业务契约",
    "description": "为 occ_website_cn 提供管理员可维护的脱敏人工验收清单，验证安装、配置、核心流程和权限边界。",
    "author": "Odoo老赵",
    "website": "https://odoocc.com",
    "support": "156277468@qq.com",
    "license": "AGPL-3",
    "depends": ["occ_website_cn"],
    "data": [
        "security/ir.model.access.csv",
        "views/acceptance_demo_templates.xml",
        "data/acceptance_checklist_data.xml",
        "views/acceptance_check_views.xml",
    ],
    "odoocc_demo": {
        "schema_version": 1,
        "category": "foundation_localization",
        "sequence": 100,
        "menu_xmlid": "occ_website_cn_test.menu_acceptance_root",
        "entry_menu_xmlid": "occ_website_cn_test.menu_acceptance_check",
        "keywords": ["中国网站", "B站视频", "国内分享", "网站备案"],
    },
    "application": False,
    "installable": True,
    "auto_install": False,
}
